<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=gbk">
<title>PostgreSQL research</title>
<style type="text/css">
.blogcnt{line-height:160%;font-size:14px;text-align:left;word-wrap:break-word;}
.blogcnt *{line-height:160%;}
.blogcnt p{margin:0 0 10px;}
.blogcnt ul,.nbw-blog ol{margin:5px 0 5px 40px;padding:0}
.blogcnt em{font-style:italic;}
.blogcnt blockquote{font-size:1em;margin:auto 0 auto 35px;}
.blogcnt img{border:0;max-width:100%;}
</style>
</head>
<body style="color:#444444;">
<h1 id="blog-Title"><a href="index.html">PostgreSQL research</a></h1>
<div id="" style="padding:0 20px;">
	<h2 id="">PostgreSQL 9.0.0 BUG FATAL:  invalid cache id: 19</h2>
	<h5 id="">2011-09-29 11:09:07&nbsp;&nbsp;&nbsp;<a href="http://blog.163.com/digoal@126/blog/static/1638770402011829104651925/" target="_blank">查看原文&gt;&gt;</a></h5>
	<div class="" id="" style="padding:0 20px;">
		<div class="blogcnt" style="width:800px;"><div>今天一个数据库( PostgreSQL 9.0.0 ) 有些记录的<span style="color: rgb(51, 51, 51); font-family: monospace; line-height: 24px; white-space: pre;"  >年龄大于{(2^31)-1百万}的记录，数据库进入错误状态，无法提供服务。</span></div><div><span style="color: rgb(51, 51, 51); font-family: monospace; line-height: 24px; white-space: pre;"  >28号的报错 （这里是系统发出警告，但是仍旧可以使用）:</span></div><div><font color="#333333"  face="monospace"  ><span style="white-space: pre;"  >2011-09-28 12:54:34.342 CST,"db_digoal","db_digoal",13647,"192.168.xxx.xxx:46914",4e2fa148.354f,3057,"INSERT",2011-07-27 13:25:28 CST,60/311573278,0,WARNING,01000,"database ""db_digoal"" must be vacuumed within 10999996 transactions",,"To avoid a database shutdown, execute a database-wide VACUUM in that database.</span></font></div><div><font color="#333333"  face="monospace"  ><span style="white-space: pre;"  >29号的报错:</span></font></div><div><div>2011-09-29 09:42:33.273 CST,,,30165,,4e83cd09.75d5,1,,2011-09-29 09:42:33 CST,138/13556266,0,ERROR,54000,"database is not accepting commands to avoid wraparound data loss in database ""db_digoal""",,"Stop the postmaster and use a standalone backend to vacuum that database.</div><div>You might also need to commit or roll back old prepared transactions.",,,,,,,""</div></div><div><br></div><div>处理这类报错可以参考我以前写过的一篇BLOG ：<a style="line-height: 22px; " href="http://blog.163.com/digoal@126/blog/static/163877040201011152042497/"  >http://blog.163.com/digoal@126/blog/static/163877040201011152042497/</a></div><div>但是今天遭遇了一个BUG，如下 :&nbsp;</div><div><div>postgres --single -D $PGDATA -p 5432 db_digoal</div><div>FATAL: &nbsp;invalid cache id: 19</div></div><div>数据库FATAL掉了。</div><div><br></div><div>把9.0.0升级到9.0.5,重新进入单用户模式，正常。</div><div><br></div><div>postgres --single -D $PGDATA -p 5432 &nbsp;db_digoal</div><div>backend&gt; vacuum full;</div><div><br></div><div>规避这类问题:</div><div>1. 加入长事务监控</div><div>2. 定期检查长事务</div><div>3. 出现问题前杀掉长事务backend</div><div><br></div><div>【参考】</div><a href="http://blog.163.com/digoal@126/blog/static/163877040201011152042497/"  >http://blog.163.com/digoal@126/blog/static/163877040201011152042497/</a><wbr><div>src/backend/utils/cache/syscache.c</div></div>
	</div>
</div>
</body>
</html>