<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=gbk">
<title>PostgreSQL research</title>
<style type="text/css">
.blogcnt{line-height:160%;font-size:14px;text-align:left;word-wrap:break-word;}
.blogcnt *{line-height:160%;}
.blogcnt p{margin:0 0 10px;}
.blogcnt ul,.nbw-blog ol{margin:5px 0 5px 40px;padding:0}
.blogcnt em{font-style:italic;}
.blogcnt blockquote{font-size:1em;margin:auto 0 auto 35px;}
.blogcnt img{border:0;max-width:100%;}
</style>
</head>
<body style="color:#444444;">
<h1 id="blog-Title"><a href="index.html">PostgreSQL research</a></h1>
<div id="" style="padding:0 20px;">
	<h2 id="">Lua error handler: error() and pcall()</h2>
	<h5 id="">2014-02-19 17:25:38&nbsp;&nbsp;&nbsp;<a href="http://blog.163.com/digoal@126/blog/static/163877040201411951058505/" target="_blank">查看原文&gt;&gt;</a></h5>
	<div class="" id="" style="padding:0 20px;">
		<div class="blogcnt" style="width:800px;"><div>pcall函数可用于调用函数, 如果函数调用成功, 返回true以及被调用函数的结果集.</div><div>如果调用失败, 返回false以及错误消息.</div><div>结合error可以方便的捕获消息和处理错误.</div><div>例如 :&nbsp;</div><div>pcall调用一个匿名函数, 结果存储到status和err全局变量, 错误消息可以是字符串, 也可以是其他数据类型, 例如表类型.</div><div>因此比较方便把当时的变量值, 错误消息, 错误代码存储到表中.</div><div><pre class="prettyprint"   ><p></p><div><font size="2"   >&gt; status, err = pcall( function() error({code = 121}) end )</font></div><div><font size="2"   >&gt; print(status)</font></div><div><font size="2"   >false</font></div><div><font size="2"   >&gt; print(err)</font></div><div><font size="2"   >table: 0x22033b0</font></div><div><font size="2"   >&gt; print(err.code)</font></div><div><font size="2"   >121</font></div><p></p></pre></div><div><br></div><div>如果函数被正常调用, 返回正常的结果</div><div><pre class="prettyprint"   ><p></p><div><div><font size="2"   >&gt; status, err,a,b,c = pcall( function(...) return ... end, 1, 2, 3 )</font></div><div><font size="2"   >&gt; print(status,err,a,b,c)</font></div><div><font size="2"   >true &nbsp; &nbsp;1 &nbsp; &nbsp; &nbsp; 2 &nbsp; &nbsp; &nbsp; 3 &nbsp; &nbsp; &nbsp; nil</font></div></div><div><font size="2"   >&gt; p = function(...) return ... end</font></div><div><div><font size="2"   >&gt; status, err,x,y,z = pcall( p, 1,2,3 )</font></div><div><font size="2"   >&gt; print(status,err,x,y,z)</font></div><div><font size="2"   >true &nbsp; &nbsp;1 &nbsp; &nbsp; &nbsp; 2 &nbsp; &nbsp; &nbsp; 3 &nbsp; &nbsp; &nbsp; nil</font></div></div><p></p></pre></div><div>注意函数的参数是在pcall的参数中传递过去的, 不是直接使用f(1,2,3). 需要注意了.</div><div><br></div><div>error和pcall通常的搭配 :&nbsp;</div><div><pre class="prettyprint"   ><p></p><div><font size="2"   >&nbsp; &nbsp; function foo ()</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; &nbsp; ...</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; if unexpected_condition then error() end</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; &nbsp; ...</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; print(a[i]) &nbsp; &nbsp;-- potential error: `a' may not be a table</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; &nbsp; ...</font></div><div><font size="2"   >&nbsp; &nbsp; end</font></div><div><font size="2"   >Then, you call foo with pcall:</font></div><div><font size="2"   >&nbsp; &nbsp; if pcall(foo) then</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; -- no errors while running `foo'</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; ...</font></div><div><font size="2"   >&nbsp; &nbsp; else</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; -- `foo' raised an error: take appropriate actions</font></div><div><font size="2"   >&nbsp; &nbsp; &nbsp; ...</font></div><div><font size="2"   >&nbsp; &nbsp; end</font></div><p></p></pre></div><div><br></div><div>[参考]</div><div>1.&nbsp;</div><div><h3 style="font-family: Verdana, Geneva, sans-serif; font-weight: normal; padding-left: 0.5em; border-left-style: solid; border-left-color: rgb(208, 208, 255); border-left-width: 1em; line-height: normal; text-align: justify;"   ><a style="background-color: rgb(248, 248, 248); padding: 8px; border: 2px solid rgb(160, 160, 160); border-top-left-radius: 8px; border-top-right-radius: 8px; border-bottom-right-radius: 8px; border-bottom-left-radius: 8px;" name="pdf-pcall" rel="nofollow"   ><code style="font-size: inherit; font-family: inherit;"   >pcall (f [, arg1, ・・・])</code></a></h3><p style="font-family: Helvetica, Arial, sans-serif; font-size: medium; line-height: normal; text-align: justify;"   >Calls function&nbsp;<code style="font-size: 12pt;"   >f</code>&nbsp;with the given arguments in&nbsp;<em>protected mode</em>. This means that any error inside&nbsp;<code style="font-size: 12pt;"   >f</code>&nbsp;is not propagated; instead,&nbsp;<code style="font-size: 12pt;"   >pcall</code>&nbsp;catches the error and returns a status code. Its first result is the status code (a boolean), which is true if the call succeeds without errors. In such case,&nbsp;<code style="font-size: 12pt;"   >pcall</code>&nbsp;also returns all results from the call, after this first result. In case of any error,<code style="font-size: 12pt;"   >pcall</code>&nbsp;returns&nbsp;<b>false</b>&nbsp;plus the error message.</p></div><div>2.&nbsp;</div><div><h3 style="font-family: Verdana, Geneva, sans-serif; font-weight: normal; padding-left: 0.5em; border-left-style: solid; border-left-color: rgb(208, 208, 255); border-left-width: 1em; line-height: normal; text-align: justify;"   ><a name="pdf-error" rel="nofollow"   >error (message [, level])</a></h3><span style="font-family: Helvetica, Arial, sans-serif; font-size: medium; line-height: normal; text-align: justify;"   >Terminates the last protected function called and returns&nbsp;</span><code style="font-size: medium; line-height: normal; text-align: justify;"   >message</code><span style="font-family: Helvetica, Arial, sans-serif; font-size: medium; line-height: normal; text-align: justify;"   >&nbsp;as the error message. Function&nbsp;</span><code style="font-size: medium; line-height: normal; text-align: justify;"   >error</code><span style="font-family: Helvetica, Arial, sans-serif; font-size: medium; line-height: normal; text-align: justify;"   >&nbsp;never returns.</span><p style="font-family: Helvetica, Arial, sans-serif; font-size: medium; line-height: normal; text-align: justify;"   >Usually,&nbsp;<code style="font-size: 12pt;"   >error</code>&nbsp;adds some information about the error position at the beginning of the message, if the message is a string. The&nbsp;<code style="font-size: 12pt;"   >level</code>&nbsp;argument specifies how to get the error position. With level&nbsp;1 (the default), the error position is where the&nbsp;<code style="font-size: 12pt;"   >error</code>&nbsp;function was called. Level&nbsp;2 points the error to where the function that called&nbsp;<code style="font-size: 12pt;"   >error</code>&nbsp;was called; and so on. Passing a level&nbsp;0 avoids the addition of error position information to the message.</p></div></div>
	</div>
</div>
</body>
</html>