<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=gbk">
<title>PostgreSQL research</title>
<style type="text/css">
.blogcnt{line-height:160%;font-size:14px;text-align:left;word-wrap:break-word;}
.blogcnt *{line-height:160%;}
.blogcnt p{margin:0 0 10px;}
.blogcnt ul,.nbw-blog ol{margin:5px 0 5px 40px;padding:0}
.blogcnt em{font-style:italic;}
.blogcnt blockquote{font-size:1em;margin:auto 0 auto 35px;}
.blogcnt img{border:0;max-width:100%;}
</style>
</head>
<body style="color:#444444;">
<h1 id="blog-Title"><a href="index.html">PostgreSQL research</a></h1>
<div id="" style="padding:0 20px;">
	<h2 id="">Ruby Study 10 : Exception Handling</h2>
	<h5 id="">2012-03-15 14:38:51&nbsp;&nbsp;&nbsp;<a href="http://blog.163.com/digoal@126/blog/static/163877040201221593521112/" target="_blank">查看原文&gt;&gt;</a></h5>
	<div class="" id="" style="padding:0 20px;">
		<div class="blogcnt" style="width:800px;"><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >exception 在程序开发中是不可或缺的部分, 程序在使用过程中总会遇到不可预知的问题, 例如可预知的访问文件的程序可能在访问过程中文件被删除或移动等. 但是总会有不可预知的, 不可能在写程序时全部规避掉.</span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >所以就有了exception handling.</span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >在Ruby中exception 是Exception calss或者它的subclass的object. 下面来详细的讲解一下异常时如何捕获exception.</span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >注意Ruby的Exception Handling分为几个层面 , 异常执行, 正常执行, 确保执行, 重试, 延迟处理等.</span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >1. rescue, Execute code when error occurs</span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >基本语法 :&nbsp;</span></div><div><pre class="prettyprint"  ><p></p><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  >begin</font></span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  >  </font></span><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px;"  ># Some code which may cause an exception</span></font></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  >rescue &lt;Exception Class&gt;</font></span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  >  </font></span><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px;"  ># Code to recover from the exception</span></font></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  >end</font></span></div><p></p></pre></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >例如 :&nbsp;</span></div><div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><pre class="prettyprint"  ><p></p><div><font size="2"  >begin</font></div><div><font size="2"  >&nbsp; &nbsp;x = 1/0</font></div><div><font size="2"  >rescue Exception</font></div><div><font size="2"  >&nbsp; &nbsp;x = 0</font></div><div><font size="2"  >&nbsp; &nbsp;puts( $!.class )</font></div><div><font size="2"  >&nbsp; &nbsp;puts( $! )</font></div><div><font size="2"  >end</font></div><div><font size="2"  >puts( x )</font></div><p></p></pre></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  >执行结果 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px;"  >ZeroDivisionError</span></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px;"  >divided by 0</span></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px;"  >0</span></font></div><p></p></pre></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  >1/0 . 1是Fixnum接收者, &nbsp;/ 是Fixnum的public instance method. 0是传入的message.&nbsp;</div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  >1除以0 当然是不允许的. 所以rescue Exception, 指捕获最大范围的异常对象.&nbsp;</div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  >$! 是一个全局变量, 存储最后一次异常的object. &nbsp;这里显然是<span style="line-height: 20px; white-space: pre;"  >ZeroDivisionError 的object.</span></div></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  ><span style="white-space: pre;"  >divided by 0 是ZeroDivisionError对象输出的消息. 可以写一个to_s返回其他消息.</span></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  ><span style="white-space: pre;"  >例如 : </span></div><div><pre class="prettyprint"  ><p><font size="2"  >class ZeroDivisionError   def to_s     return "you cann't divided by 0"   end end  begin    x = 1/0 rescue Exception    x = 0    puts( $!.class )    puts( $! ) end puts( x )</font></p></pre></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  ><span style="line-height: 20px; white-space: pre;"  >执行结果 : </span></div><div><pre class="prettyprint"  ><p><font size="2"  >ZeroDivisionError you cann't divided by 0 0</font></p></pre></div><div><span style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small; white-space: pre;"  >$! 这个全局变量, 如果不想使用的话, 也可以用一个</span><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px; white-space: pre;"  >assoc operator 也就是=&gt; 赋予捕获到的Exception object给其他的变量.</span></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px; white-space: pre;"  >例如 : </span></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >def calc( val1, val2 )</font></div><div><font size="2"  >&nbsp; &nbsp; return val1 / val2</font></div><div><font size="2"  >end</font></div><div><font size="2"  ><br></font></div><div><font size="2"  >begin</font></div><div><font size="2"  >&nbsp; result = calc(10,0)</font></div><div><font size="2"  >rescue Exception =&gt; e1</font></div><div><font size="2"  >&nbsp; puts(e1.class)</font></div><div><font size="2"  >&nbsp; puts(e1)</font></div><div><font size="2"  >&nbsp; result = 0</font></div><div><font size="2"  >end</font></div><div><font size="2"  >puts(result)</font></div><p></p></pre></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  ><span style="line-height: 20px; white-space: pre;"  >执行结果 : </span></div><div><pre class="prettyprint"  ><p><font size="2"  >ZeroDivisionError divided by 0 0</font></p></pre></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  ><span style="line-height: 20px; white-space: pre;"  >接下来我们来看看Exception的继承关系 : </span></div><div><pre class="prettyprint"  ><p><font size="2"  >def putclass(obj1)   p(obj1.superclass)   if obj1.superclass != nil then putclass(obj1.superclass) end end  putclass(ZeroDivisionError)</font></p></pre></div><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px; font-size: small;"  ><span style="line-height: 20px; white-space: pre;"  >输出结果 : </span></div><div><pre class="prettyprint"  ><p><font size="2"  >StandardError Exception Object BasicObject nil</font></p></pre></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px; white-space: pre;"  >接下来看看另几种错误,NoMethodError 和 TypeError.</span></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px; white-space: pre;"  >例如 : </span></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><div style="line-height: 20px; white-space: pre;"  ><pre class="prettyprint"  ><p></p><div>def putclass(obj1)</div><div>&nbsp; p(obj1.superclass)</div><div>&nbsp; if obj1.superclass != nil then putclass(obj1.superclass) end</div><div>end</div><div><br></div><div>def calc( val1, val2 )</div><div>&nbsp; &nbsp; return val1 / val2</div><div>end</div><div><br></div><div>begin</div><div>&nbsp; result = calc("a",0)</div><div>rescue Exception =&gt; e1</div><div>&nbsp; puts(e1.class)</div><div>&nbsp; puts(e1)</div><div>&nbsp; result = 0</div><div>end</div><div>puts(result)</div><div><br></div><div>putclass(e1.class)</div><div><br></div><div>begin</div><div>&nbsp; result = calc(10,"a")</div><div>rescue Exception =&gt; e1</div><div>&nbsp; puts(e1.class)</div><div>&nbsp; puts(e1)</div><div>&nbsp; result = 0</div><div>end</div><div>puts(result)</div><div><br></div><div>putclass(e1.class)</div><p></p></pre></div><div style="line-height: 20px; white-space: pre;"  >输出结果 : </div><div><pre class="prettyprint"  ><p>NoMethodError undefined method `/' for "a":String 0 NameError StandardError Exception Object BasicObject nil TypeError String can't be coerced into Fixnum 0 StandardError Exception Object BasicObject nil</p></pre></div><div><span style="white-space: pre;"  >在一个块(begin end)中可以写多个rescue捕获, 当捕获到异常匹配后则不再进行下一个rescue. </span></div><div><span style="white-space: pre;"  >所以要把范围小的写在前面, 范围大的异常写在后面. 例如 : </span></div><div><pre class="prettyprint"  ><p>def calc( val1, val2 )     begin         result = val1 / val2     rescue TypeError, NoMethodError =&gt; e         puts( e.class )         puts( e )         puts( "One of the values is not a number!" )         result = nil     rescue Exception =&gt; e         puts( e.class )         puts( e )         result = nil     end     return result end  p calc("a",1)</p></pre></div><div><span style="white-space: pre;"  >执行结果 : </span></div><div><pre class="prettyprint"  ><p>NoMethodError undefined method `/' for "a":String One of the values is not a number! nil</p></pre></div><div><span style="white-space: pre;"  >如果把上面的两个rescue倒过来写的话, 后面的rescue就不可能被执行到.因为Exception包含了TypeError和NoMethodError.</span></div><div><span style="white-space: pre;"  ><br></span></div></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >2. ensure, Execute code whether or not an error occurs</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >ensure表示不管有没有异常都必须执行的代码.</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >例如打开了一个文件, 不管有没有异常都要关闭它. 又或者最后要回到程序执行时的目录.</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >startdir = Dir.getwd</font></div><div><font size="2"  >begin</font></div><div><font size="2"  >&nbsp; &nbsp;Dir.chdir( "X:\\" )  # 假设这个目录不存在或为空</font></div><div><font size="2"  >&nbsp; &nbsp;puts( `dir` )</font></div><div><font size="2"  >rescue Exception =&gt; e</font></div><div><font size="2"  >&nbsp; &nbsp;puts e.class</font></div><div><font size="2"  >&nbsp; &nbsp;puts e</font></div><div><font size="2"  >ensure</font></div><div><font size="2"  >&nbsp; &nbsp;Dir.chdir( startdir )</font></div><div><font size="2"  >end</font></div><div><font size="2"  ><br></font></div><div><font size="2"  >p startdir</font></div><div><font size="2"  >p Dir.getwd</font></div><p></p></pre></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >执行结果 :&nbsp;</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >Errno::ENOENT</font></div><div><font size="2"  >No such file or directory - X:\</font></div><div><font size="2"  >"C:/Users/digoal/Desktop"</font></div><div><font size="2"  >"C:/Users/digoal/Desktop"</font></div><p></p></pre></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >再来测试一个,</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  ># cat test.rb</font></div><div><font size="2"  >#!/opt/ruby/bin/ruby</font></div><div><font size="2"  >f = File.new( "text" )</font></div><div><font size="2"  >begin</font></div><div><font size="2"  >&nbsp; &nbsp; for i in (1..6) do</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; puts("line number: #{f.lineno}")</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; line = f.gets.chomp</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; num = line.to_i</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; puts( "Line '#{line}' is converted to #{num}" )</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; puts( 100 / num )</font></div><div><font size="2"  >&nbsp; &nbsp; end</font></div><div><font size="2"  >rescue Exception =&gt; e</font></div><div><font size="2"  >&nbsp; &nbsp; puts( e.class )</font></div><div><font size="2"  >&nbsp; &nbsp; puts( e )</font></div><div><font size="2"  >ensure</font></div><div><font size="2"  >&nbsp; &nbsp; f.close</font></div><div><font size="2"  >&nbsp; &nbsp; puts( "File closed" )</font></div><div><font size="2"  >end</font></div><div><font size="2"  ># text文件的最后一行是字符串, 无法转换为Fixnum,&nbsp;因此会捕获到异常, </font></div><div><font size="2"  ># 不管有没有异常我们都需要关闭这个文件. 因此ensure代码中写了f.close</font></div><div><div><font size="2"  ># cat text</font></div><div><font size="2"  >1</font></div><div><font size="2"  >2</font></div><div><font size="2"  >3</font></div><div><font size="2"  >4</font></div><div><font size="2"  >5</font></div><div><font size="2"  >jd</font></div></div><p></p></pre></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >执行结果 :&nbsp;</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >line number: 0</font></div><div><font size="2"  >Line '1' is converted to 1</font></div><div><font size="2"  >100</font></div><div><font size="2"  >line number: 1</font></div><div><font size="2"  >Line '2' is converted to 2</font></div><div><font size="2"  >50</font></div><div><font size="2"  >line number: 2</font></div><div><font size="2"  >Line '3' is converted to 3</font></div><div><font size="2"  >33</font></div><div><font size="2"  >line number: 3</font></div><div><font size="2"  >Line '4' is converted to 4</font></div><div><font size="2"  >25</font></div><div><font size="2"  >line number: 4</font></div><div><font size="2"  >Line '5' is converted to 5</font></div><div><font size="2"  >20</font></div><div><font size="2"  >line number: 5</font></div><div><font size="2"  >Line 'jd' is converted to 0</font></div><div><font size="2"  >ZeroDivisionError</font></div><div><font size="2"  >divided by 0</font></div><div><font size="2"  >File closed</font></div><p></p></pre></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >这里用到了File的几个public instance method, lineno, gets. 实际上这两个方法是来自IO的.</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >File是IO的subclass.</span></font></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 20px;"  ><br></span></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >3. else, Execute code when no error occurs</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >else 指当begin后面的代码正常运行的情况下, 则执行else中的代码, 格式 :&nbsp;</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >begin</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; # code which may cause an exception &nbsp;&nbsp;</font></div><div><font size="2"  >rescue [Exception Type]</font></div><div><font size="2"  >else &nbsp; &nbsp;# optional section executes if no exception occurs</font></div><div><font size="2"  >ensure &nbsp;# optional exception always executes</font></div><div><font size="2"  >end</font></div><p></p></pre></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >例如 :&nbsp;</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><span style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >def doCalc( aNum )</span></div><div><font size="2"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  ><div>&nbsp; &nbsp;begin</div><div>&nbsp; &nbsp; &nbsp; result = 100 / aNum.to_i</div><div>&nbsp; &nbsp;rescue Exception =&gt; e &nbsp; &nbsp; # executes when there is an error</div><div>&nbsp; &nbsp; &nbsp; result = 0</div><div>&nbsp; &nbsp; &nbsp; msg = "Error: " + e.to_s</div><div>&nbsp; &nbsp;else &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;# executes when there is no error</div><div>&nbsp; &nbsp; &nbsp; msg = "Result = #{result}"</div><div>&nbsp; &nbsp;ensure &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;# always executes</div><div>&nbsp; &nbsp; &nbsp; msg = "You entered '#{aNum}'. " + msg</div><div>&nbsp; &nbsp;end</div><div>&nbsp; &nbsp;return msg</div><div>end</div><div><br></div><div>p doCalc("a")</div><div>p doCalc(1)</div></font></font></div><p></p></pre></div><div><font size="2"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  ><div>执行结果 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div>"You entered 'a'. Error: divided by 0"</div><div>"You entered '1'. Result = 100"</div><p></p></pre></div><div><br></div></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >4. Error numbers</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >Ruby的Exception子类很多, 也分得比较细.</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >有一个比较特别的Module是Errno.&nbsp;</span></font></font><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >Errno包含很多常量, 这些常量的值可以通过Errno::常量名::Errno来获取.&nbsp;</span></div><div><span style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; font-size: small;"  >同时这些常量又是Exception的下下级子类. 例如我们来看一个例子 :&nbsp;</span></div><div><font size="2"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  ><div><pre class="prettyprint"  ><p></p><div>def showFamily( aClass )</div><div>&nbsp; &nbsp; if (aClass != nil) then &nbsp; &nbsp;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( "#{aClass} :: about to recurse with aClass.superclass = #{aClass.superclass.inspect}" )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; showFamily( aClass.superclass )</div><div>&nbsp; &nbsp; end</div><div>end</div><div><br></div><div>def chDisk( aChar )</div><div>&nbsp; &nbsp; startdir = Dir.getwd</div><div>&nbsp; &nbsp; begin</div><div>&nbsp; &nbsp; &nbsp; &nbsp; Dir.chdir( "#{aChar}:\\" )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( `dir` )</div><div>&nbsp; &nbsp; rescue Exception =&gt; e</div><div>&nbsp; &nbsp; &nbsp; &nbsp; showFamily( e.class ) # to see ancestors, uncomment&nbsp;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts e.class &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # ...and comment out this</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts e</div><div>&nbsp; &nbsp; &nbsp; &nbsp; ensure</div><div>&nbsp; &nbsp; &nbsp; &nbsp; Dir.chdir( startdir )</div><div>&nbsp; &nbsp; end &nbsp; &nbsp;</div><div>end</div><div>chDisk( "F" )  # F是我的光驱, 没放光盘,</div><div>chDisk( "X" )  # X是一个不存在的盘,</div><div>chDisk( "ABC" )  # ABC则是一个格式错误的盘符.</div><p></p></pre></div><div>执行结果 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div>Errno::EACCES :: about to recurse with aClass.superclass = SystemCallError</div><div>SystemCallError :: about to recurse with aClass.superclass = StandardError</div><div>StandardError :: about to recurse with aClass.superclass = Exception</div><div>Exception :: about to recurse with aClass.superclass = Object</div><div>Object :: about to recurse with aClass.superclass = BasicObject</div><div>BasicObject :: about to recurse with aClass.superclass = nil</div><div>Errno::EACCES</div><div>Permission denied - F:\</div><div>Errno::ENOENT :: about to recurse with aClass.superclass = SystemCallError</div><div>SystemCallError :: about to recurse with aClass.superclass = StandardError</div><div>StandardError :: about to recurse with aClass.superclass = Exception</div><div>Exception :: about to recurse with aClass.superclass = Object</div><div>Object :: about to recurse with aClass.superclass = BasicObject</div><div>BasicObject :: about to recurse with aClass.superclass = nil</div><div>Errno::ENOENT</div><div>No such file or directory - X:\</div><div>Errno::EINVAL :: about to recurse with aClass.superclass = SystemCallError</div><div>SystemCallError :: about to recurse with aClass.superclass = StandardError</div><div>StandardError :: about to recurse with aClass.superclass = Exception</div><div>Exception :: about to recurse with aClass.superclass = Object</div><div>Object :: about to recurse with aClass.superclass = BasicObject</div><div>BasicObject :: about to recurse with aClass.superclass = nil</div><div>Errno::EINVAL</div><div>Invalid argument - ABC:\</div><p></p></pre></div><div>Errno API中的介绍 :&nbsp;</div><div><div id="description"  > <p>Ruby exception objects are subclasses of <tt>Exception</tt>. However,  operating systems typically report errors using plain integers. <a rel="nofollow" href=""  >Module</a> <tt>Errno</tt> is created dynamically to map these  operating system errors to Ruby classes, with each error number generating its  own subclass of <tt>SystemCallError</tt>. As the subclass is created in module  <tt>Errno</tt>, its name will start <tt>Errno::</tt>. </p> <p>The names of the <tt>Errno::</tt> classes depend on the environment in which  Ruby runs. On a typical Unix or Windows platform, there are <tt>Errno</tt>  classes such as <tt>Errno::EACCES</tt>, <tt>Errno::EAGAIN</tt>,  <tt>Errno::EINTR</tt>, and so on. </p> <p>The integer operating system error number corresponding to a particular error  is available as the class constant  <tt>Errno::</tt><em>error</em><tt>::Errno</tt>. </p><pre>   Errno::EACCES::Errno   #=&gt; 13    Errno::EAGAIN::Errno   #=&gt; 11    Errno::EINTR::Errno    #=&gt; 4 </pre> <p>The full list of operating system errors on your particular platform are  available as the constants of <tt>Errno</tt>. </p><pre>   Errno.constants   #=&gt; :E2BIG, :EACCES, :EADDRINUSE, :EADDRNOTAVAIL, ...</pre></div></div><div><pre class="prettyprint"  ><p></p><div>p Errno.constants.sort</div><div>[:E2BIG, :EACCES, :EADDRINUSE, :EADDRNOTAVAIL, :EADV, :EAFNOSUPPORT, :EAGAIN, :EALREADY, :EAUTH, :EBADE, :EBADF, :EBADFD, :EBADMSG, :EBADR, :EBADRPC, :EBADRQC, :EBADSLT, :EBFONT, :EBUSY, :ECANCELED, :ECHILD, :ECHRNG, :ECOMM, :ECONNABORTED, :ECONNREFUSED, :ECONNRESET, :EDEADLK, :EDEADLOCK, :EDESTADDRREQ, :EDOM, :EDOOFUS, :EDOTDOT, :EDQUOT, :EEXIST, :EFAULT, :EFBIG, :EFTYPE, :EHOSTDOWN, :EHOSTUNREACH, :EIDRM, :EILSEQ, :EINPROGRESS, :EINTR, :EINVAL, :EIO, :EIPSEC, :EISCONN, :EISDIR, :EISNAM, :EKEYEXPIRED, :EKEYREJECTED, :EKEYREVOKED, :EL2HLT, :EL2NSYNC, :EL3HLT, :EL3RST, :ELIBACC, :ELIBBAD, :ELIBEXEC, :ELIBMAX, :ELIBSCN, :ELNRNG, :ELOOP, :EMEDIUMTYPE, :EMFILE, :EMLINK, :EMSGSIZE, :EMULTIHOP, :ENAMETOOLONG, :ENAVAIL, :ENEEDAUTH, :ENETDOWN, :ENETRESET, :ENETUNREACH, :ENFILE, :ENOANO, :ENOATTR, :ENOBUFS, :ENOCSI, :ENODATA, :ENODEV, :ENOENT, :ENOEXEC, :ENOKEY, :ENOLCK, :ENOLINK, :ENOMEDIUM, :ENOMEM, :ENOMSG, :ENONET, :ENOPKG, :ENOPROTOOPT, :ENOSPC, :ENOSR, :ENOSTR, :ENOSYS, :ENOTBLK, :ENOTCONN, :ENOTDIR, :ENOTEMPTY, :ENOTNAM, :ENOTRECOVERABLE, :ENOTSOCK, :ENOTSUP, :ENOTTY, :ENOTUNIQ, :ENXIO, :EOPNOTSUPP, :EOVERFLOW, :EOWNERDEAD, :EPERM, :EPFNOSUPPORT, :EPIPE, :EPROCLIM, :EPROCUNAVAIL, :EPROGMISMATCH, :EPROGUNAVAIL, :EPROTO, :EPROTONOSUPPORT, :EPROTOTYPE, :ERANGE, :EREMCHG, :EREMOTE, :EREMOTEIO, :ERESTART, :ERFKILL, :EROFS, :ERPCMISMATCH, :ESHUTDOWN, :ESOCKTNOSUPPORT, :ESPIPE, :ESRCH, :ESRMNT, :ESTALE, :ESTRPIPE, :ETIME, :ETIMEDOUT, :ETOOMANYREFS, :ETXTBSY, :EUCLEAN, :EUNATCH, :EUSERS, :EWOULDBLOCK, :EXDEV, :EXFULL, :NOERROR]</div><p></p></pre></div></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >查询Errno常量值 :&nbsp;</span></font></font></div><div><font size="2"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  ><div style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  ><pre class="prettyprint"  ><p></p><div style="font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  >for err in Errno.constants.sort do&nbsp;</div><div style="font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  >&nbsp; &nbsp;errnum = eval( "Errno::#{err}::Errno" )</div><div style="font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  >&nbsp; &nbsp;print( "#{err} #{errnum} ," )&nbsp;</div><div style="font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  >end</div><div style="font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  >结果</div><div>E2BIG 7 ,EACCES 13 ,EADDRINUSE 10048 ,EADDRNOTAVAIL 10049 ,EADV 0 ,EAFNOSUPPORT 10047 ,EAGAIN 11 ,EALREADY 10037 ,EAUTH 0 ,EBADE 0 ,EBADF 9 ,EBADFD 0 ,EBADMSG 0 ,EBADR 0 ,EBADRPC 0 ,EBADRQC 0 ,EBADSLT 0 ,EBFONT 0 ,EBUSY 16 ,ECANCELED 0 ,ECHILD 10 ,ECHRNG 0 ,ECOMM 0 ,ECONNABORTED 10053 ,ECONNREFUSED 10061 ,ECONNRESET 10054 ,EDEADLK 36 ,EDEADLOCK 36 ,EDESTADDRREQ 10039 ,EDOM 33 ,EDOOFUS 0 ,EDOTDOT 0 ,EDQUOT 10069 ,EEXIST 17 ,EFAULT 14 ,EFBIG 27 ,EFTYPE 0 ,EHOSTDOWN 10064 ,EHOSTUNREACH 10065 ,EIDRM 0 ,EILSEQ 42 ,EINPROGRESS 10036 ,EINTR 4 ,EINVAL 22 ,EIO 5 ,EIPSEC 0 ,EISCONN 10056 ,EISDIR 21 ,EISNAM 0 ,EKEYEXPIRED 0 ,EKEYREJECTED 0 ,EKEYREVOKED 0 ,EL2HLT 0 ,EL2NSYNC 0 ,EL3HLT 0 ,EL3RST 0 ,ELIBACC 0 ,ELIBBAD 0 ,ELIBEXEC 0 ,ELIBMAX 0 ,ELIBSCN 0 ,ELNRNG 0 ,ELOOP 10062 ,EMEDIUMTYPE 0 ,EMFILE 24 ,EMLINK 31 ,EMSGSIZE 10040 ,EMULTIHOP 0 ,ENAMETOOLONG 38 ,ENAVAIL 0 ,ENEEDAUTH 0 ,ENETDOWN 10050 ,ENETRESET 10052 ,ENETUNREACH 10051 ,ENFILE 23 ,ENOANO 0 ,ENOATTR 0 ,ENOBUFS 10055 ,ENOCSI 0 ,ENODATA 0 ,ENODEV 19 ,ENOENT 2 ,ENOEXEC 8 ,ENOKEY 0 ,ENOLCK 39 ,ENOLINK 0 ,ENOMEDIUM 0 ,ENOMEM 12 ,ENOMSG 0 ,ENONET 0 ,ENOPKG 0 ,ENOPROTOOPT 10042 ,ENOSPC 28 ,ENOSR 0 ,ENOSTR 0 ,ENOSYS 40 ,ENOTBLK 0 ,ENOTCONN 10057 ,ENOTDIR 20 ,ENOTEMPTY 41 ,ENOTNAM 0 ,ENOTRECOVERABLE 0 ,ENOTSOCK 10038 ,ENOTSUP 0 ,ENOTTY 25 ,ENOTUNIQ 0 ,ENXIO 6 ,EOPNOTSUPP 10045 ,EOVERFLOW 0 ,EOWNERDEAD 0 ,EPERM 1 ,EPFNOSUPPORT 10046 ,EPIPE 32 ,EPROCLIM 10067 ,EPROCUNAVAIL 0 ,EPROGMISMATCH 0 ,EPROGUNAVAIL 0 ,EPROTO 0 ,EPROTONOSUPPORT 10043 ,EPROTOTYPE 10041 ,ERANGE 34 ,EREMCHG 0 ,EREMOTE 10071 ,EREMOTEIO 0 ,ERESTART 0 ,ERFKILL 0 ,EROFS 30 ,ERPCMISMATCH 0 ,ESHUTDOWN 10058 ,ESOCKTNOSUPPORT 10044 ,ESPIPE 29 ,ESRCH 3 ,ESRMNT 0 ,ESTALE 10070 ,ESTRPIPE 0 ,ETIME 0 ,ETIMEDOUT 10060 ,ETOOMANYREFS 10059 ,ETXTBSY 0 ,EUCLEAN 0 ,EUNATCH 0 ,EUSERS 10068 ,EWOULDBLOCK 10035 ,EXDEV 18 ,EXFULL 0 ,NOERROR 0 ,</div><p></p></pre></div></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  ><br></span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >5. retry, Attempt to Execute code again after an error</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >如果想在捕获到异常后重试begin后面的代码, 可以在rescue中写上retry. 例如 :&nbsp;</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >#!/opt/ruby/bin/ruby</font></div><div><font size="2"  >def doCalc</font></div><div><font size="2"  >&nbsp; &nbsp; begin</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; print( "Enter a number: " )</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; aNum = gets().chomp()</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; result = 100 / aNum.to_i</font></div><div><font size="2"  >&nbsp; &nbsp; rescue Exception =&gt; e</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; result = 0</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; puts( "Error: " + e.to_s + "\nPlease try again." )    # Ruby 1.9如果要在字符连接中使用Exception的返回值, 需要使用to_s方法.</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; retry &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; # retry on exception</font></div><div><font size="2"  >&nbsp; &nbsp; else</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; msg = "Result = #{result}"</font></div><div><font size="2"  >&nbsp; &nbsp; ensure</font></div><div><font size="2"  >&nbsp; &nbsp; &nbsp; &nbsp; msg = "You entered '#{aNum}'. " + msg</font></div><div><font size="2"  >&nbsp; &nbsp; end</font></div><div><font size="2"  >&nbsp; &nbsp; return msg</font></div><div><font size="2"  >end</font></div><div><font size="2"  >doCalc</font></div><p></p></pre></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >执行结果 :&nbsp;</span></font></font></div><div><pre class="prettyprint"  ><p></p><div><font size="2"  >./test.rb&nbsp;</font></div><div><font size="2"  >Enter a number: 0</font></div><div><font size="2"  >Error: divided by 0</font></div><div><font size="2"  >Please try again.</font></div><div><font size="2"  >Enter a number: "1"</font></div><div><font size="2"  >Error: divided by 0</font></div><div><font size="2"  >Please try again.</font></div><div><font size="2"  >Enter a number: a</font></div><div><font size="2"  >Error: divided by 0</font></div><div><font size="2"  >Please try again.</font></div><div><font size="2"  >Enter a number: 10</font></div><p></p></pre></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 23px;"  >为了防止死循环, 可以加一个限制重试的次数.</span></font></div><div><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  size="2"  ><span style="line-height: 23px;"  ><div><pre class="prettyprint"  ><p></p><div>#!/opt/ruby/bin/ruby</div><div>def doCalc</div><div>&nbsp; &nbsp; tries = 0</div><div>&nbsp; &nbsp; begin</div><div>&nbsp; &nbsp; &nbsp; &nbsp; tries += 1</div><div>&nbsp; &nbsp; &nbsp; &nbsp; print( "Enter a number: " )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; aNum = gets().chomp()</div><div>&nbsp; &nbsp; &nbsp; &nbsp; result = 100 / aNum.to_i &nbsp;&nbsp;</div><div>&nbsp; &nbsp; rescue Exception =&gt; e &nbsp; &nbsp; &nbsp;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; msg = "Error: " + e.to_s</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( msg )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( "tries = #{tries}" )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; result = 0 &nbsp; &nbsp; &nbsp;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; if tries &lt; 3 then # set a fixed number of retries</div><div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;retry&nbsp;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; end &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</div><div>&nbsp; &nbsp; else</div><div>&nbsp; &nbsp; &nbsp; &nbsp; msg = "Result = #{result}"</div><div>&nbsp; &nbsp; ensure</div><div>&nbsp; &nbsp; &nbsp; &nbsp; msg = "You entered '#{aNum}'. " + msg</div><div>&nbsp; &nbsp; end</div><div>&nbsp; &nbsp; return msg</div><div>end</div><div>doCalc</div><p></p></pre></div><div>执行结果 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div>./test.rb&nbsp;</div><div>Enter a number: a</div><div>Error: divided by 0</div><div>tries = 1</div><div>Enter a number: b</div><div>Error: divided by 0</div><div>tries = 2</div><div>Enter a number: c</div><div>Error: divided by 0</div><div>tries = 3</div><p></p></pre></div></span></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  ><br></span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >6. raise, Reactivate a Handled Error</span></font></font></div><font size="2"  style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53; line-height: 23px;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  ><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >最后要说的是raise, raise是 Kernel的一个public instance method.</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >详细的说明 :&nbsp;</span></font></font></div><div><div jquery="107"  ><span>raise raise(string) raise(exception [, string [, array]])  fail fail(string) fail(exception [, string [, array]])</span> <span>click to toggle source</span> </div> <div jquery="44"  > <p>With no arguments, raises the exception in <tt>$!</tt> or raises a  <tt>RuntimeError</tt> if <tt>$!</tt> is <tt>nil</tt>. With a single  <tt>String</tt> argument, raises a <tt>RuntimeError</tt> with the string as a  message. Otherwise, the first parameter should be the name of an  <tt>Exception</tt> class (or an object that returns an <tt>Exception</tt> object  when sent an <tt>exception</tt> message). The optional second parameter sets the  message associated with the exception, and the third parameter is an array of  callback information. Exceptions are caught by the <tt>rescue</tt> clause of  <tt>begin...end</tt> blocks. </p><pre>   raise "Failed to create socket"    raise ArgumentError, "No parameters", caller</pre></div></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >例子1 :&nbsp;</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  ><div><pre class="prettyprint"  ><p></p><div>begin</div><div>&nbsp; &nbsp; raise ZeroDivisionError.new( "I'm afraid you divided by Zero" )</div><div>rescue Exception =&gt; e</div><div>&nbsp; &nbsp; puts( e.class )</div><div>&nbsp; &nbsp; puts( "message: " + e.to_s )</div><div>end</div><p></p></pre></div><div>执行结果 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div>ZeroDivisionError</div><div>message: I'm afraid you divided by Zero</div><p></p></pre></div></span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  >例子2 :&nbsp;</span></font></font></div><div><font size="2"  style="line-height: 23px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font color="#333333"  face="Arial, Helvetica, simsun, u5b8bu4f53"  style="line-height: 23px;"  ><span style="line-height: 23px;"  ><div><pre class="prettyprint"  ><p></p><div>class NoNameError &lt; Exception</div><div>&nbsp; &nbsp; def to_str</div><div>&nbsp; &nbsp; &nbsp; &nbsp; "No Name given!"</div><div>&nbsp; &nbsp; end</div><div>end</div><div>def sayHello( aName )</div><div>&nbsp; &nbsp; begin</div><div>&nbsp; &nbsp; &nbsp; &nbsp; if (aName == "") or (aName == nil) then</div><div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;raise NoNameError&nbsp;</div><div>&nbsp; &nbsp; &nbsp; &nbsp; end</div><div>&nbsp; &nbsp; rescue Exception =&gt; e</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e.class )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( "error message: " + e.to_s )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e.backtrace )</div><div>&nbsp; &nbsp; else</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( "Hello #{aName}" )</div><div>&nbsp; &nbsp; end</div><div>end</div><div>sayHello(nil)</div><p></p></pre></div><div>执行结果 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div>NoNameError</div><div>error message: NoNameError</div><div>C:/Users/digoal/Desktop/new.rb:9:in `sayHello'</div><div>C:/Users/digoal/Desktop/new.rb:19:in `&lt;main&gt;'</div><p></p></pre></div><div>这里的backtrace是Exception的public instance method.</div><div>详细解释 :&nbsp;</div><div><div jquery="14"  ><span>backtrace → array</span> <span>click to toggle source</span> </div> <div jquery="5"  > <p>Returns any backtrace associated with the exception. The backtrace is an  array of strings, each containing either ``filename:lineNo: in `method’’’ or  ``filename:lineNo.’‘ </p><pre><pre class="prettyprint"  ><p>   def a      raise "boom"    end     def b      a()    end     begin      b()    rescue =&gt; detail      print detail.backtrace.join("\n")    end</p></pre></pre> <p><em>produces:</em> </p><pre><pre class="prettyprint"  ><p>   prog.rb:2:in `a'    prog.rb:6:in `b'    prog.rb:10</p></pre></pre></div></div></span></font></font></div><div><br></div><div>7. omitting begin and end</div><div>使用异常捕获时, 在方法,Class以及Module里面可以不写begin和end.</div><div>例如 :&nbsp;</div><div><pre class="prettyprint"  ><p></p><div>def calc</div><div>&nbsp; &nbsp; &nbsp; &nbsp; result = 1/0</div><div>&nbsp; &nbsp; rescue Exception =&gt; e</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e.class )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; result = nil</div><div>&nbsp; &nbsp; return result</div><div>end</div><div><br></div><div>class X</div><div>&nbsp; &nbsp; &nbsp; &nbsp; @@x = 1/0</div><div>&nbsp; &nbsp; rescue Exception =&gt; e</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e.class )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e )</div><div>end</div><div><br></div><div>module Y</div><div>&nbsp; &nbsp; &nbsp; &nbsp; @@x = 1/0</div><div>&nbsp; &nbsp; rescue Exception =&gt; e</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e.class )</div><div>&nbsp; &nbsp; &nbsp; &nbsp; puts( e )</div><div>end</div><p></p></pre></div><div><br></div><div>最后不要混淆了catch,throw和异常捕获.</div><div>Ruby中catch和throw的用法类似别的编程语言的goto. 而不是异常捕获</div><div><br></div>【参考】</span></font></font><div style="line-height: 25px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  style="line-height: 23px;"  >The Book Of Ruby</font></div><div style="line-height: 25px; color: rgb(51, 51, 51); font-family: Arial, Helvetica, simsun, u5b8bu4f53;"  ><font size="2"  style="line-height: 23px;"  >Ruby 1.9.3 API</font></div><wbr></div>
	</div>
</div>
</body>
</html>